### ISSUE TITLE
The plugin is kicking me even though I am connecting through WaterdogPE proxy

### ISSUE THREAD

**Issue by ClydeNoIQ** [xxAROX/WaterdogPE-LoginExtras-Fix#12]
### What should happened?

The plugin would've have gotten the xuid and ip of the player

### What actual happened?

The plugin kicked me saying I am outside WaterdogPE proxy even though I am connecting through the WaterdogPE proxy

### Steps to reproduce

1. Put the plugin into your server and restart it
2. Put the server on a wdpe proxy with login extras on
3. Join the server

### Error

None

**Comment by ClydeNoIQ** [comment]
![Screenshot_20240213_071735_One UI Home](https://github.com/xxAROX/WaterdogPE-LoginExtras-Fix/assets/86055764/5046d49e-af6b-4240-8d53-72bbe804ef69)

**Comment by xxAROX** [comment]
Could you please provide the config.yml from the `plugin_data` folder?

**Comment by xxAROX** [comment]
*And sorry for my late reply :^)*

**Comment by xxAROX** [comment]
@ClydeplayzYT590

**Comment by Nat392** [comment]
Hello @xxAROX,

I have the same issue :

```yml
---
config-version: 1.5.3
force-players-to-waterdog: true
kick-message: Please use the lobby
waterdog-bind-address: "172.18.0.1"
...
```
